import { StyleSheet } from "react-native"
export const styles = StyleSheet.create({
    top:{
        width:"100%",
        height:70,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        paddingHorizontal:10
    },
    text:{
        fontSize:26,
        fontWeight:'800',
        color:'#000'
    },
    text2:{
        fontSize:12,
       textAlign:'center',
       width:'80%'
    },
    title:{
        fontSize:20,
        fontWeight:'600',
        color:'#000'
    },
    card:{
flexDirection:'row',
justifyContent:'space-between'
    }
})